# Server Port, Context
server:
    port: 8080
    servlet:
        contextPath: /blink

# SpringBoot Common Configuration
spring:
    application:
        name: BLINK-WEB
         
    profiles:
        active: local
        
    datasource:
        # DataSource Config
        platform: postgres
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: new1234@
        
    # Tymeleaf Config
    thymeleaf:
        cache: false
        enabled: true
        mode: LEGACYHTML5
        prefix: classpath:/templates/
        suffix: .html
        
        
# Mybatis Config
mybatis:
    type-aliases-package: com.kt.blink.biz
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        lazyLoadingEnabled: true
        aggressiveLazyLoading: false
        mapUnderscoreToCamelCase: true

# Logging config
logging:
    config: classpath:logback-spring.xml
    path: log

# Property Encryption
jasypt:
    encryptor:
      bean: encryptorBean
    
# custom profile proerties
blink:
    jasyptKey: Ymxpbms=
    aesKey: YmxvY2tjaGFuaW4tcmVhbHRpbWUtc2V0dGxlbWVudC0=
    aesVector: aW5pdGlhbGl6ZXZhbHVlLQ==
    scheduler:
        findTodoCron: 0 0/5 * * * ?
    upload:
        maxFileSize: 10485760
    board:
        fileUploadLocation: /upload/
    notice:
        fileUploadLocation: /upload/
    gateway:     
        url: http://localhost:8090/api/service/
        notecreate: publishCreditDebitNote
        invostat: changeInvocStatus
        contractSend: contractSend
        contractAgree: contractAgree
        contractExpire: contractExpire
        
        