class ErrorCodes {}

ErrorCodes.ERR_MISSING_PARAMETER = 'ERR_MISSING_PARAMETER';
ErrorCodes.ERR_NOT_FOUND = 'ERR_NOT_FOUND';
ErrorCodes.ERR_DUPLICATE_ENTRY = 'ERR_DUPLICATE_ENTRY';
ErrorCodes.ERR_VALIDATION = 'ERR_VALIDATION';
ErrorCodes.ERR_PRIVATE_DATA = 'ERR_PRIVATE_DATA';
ErrorCodes.ERR_SIGNATURE = 'ERR_SIGNATURE';
ErrorCodes.ERR_CA_IDENTITY = 'ERR_CA_IDENTITY';
ErrorCodes.ERR_NETWORK_DISCOVERY = 'ERR_NETWORK_DISCOVERY';
ErrorCodes.ERR_BAD_REQUEST = 'ERR_BAD_REQUEST';
ErrorCodes.ERR_FORBIDDEN = 'ERR_FORBIDDEN';
ErrorCodes.ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR';

module.exports = ErrorCodes;
